[source]
# Directory containing Markdown files to be built
sourceDirectory = "./src"
# Path to an HTML template file
htmlTemplate = "./template.html"

[output]
# Directory to place compiled HTML files
outputDirectory = "./dist"
# True if you want kissg to build an index.html containing a list of all pages
buildIndex = true
# Title to use for the index page
indexTitle = "Index"